<a href="https://colab.research.google.com/github/toriqultonu/Learning_PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

In [ ]:
import torch
print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors

### Creating Tensors

In [ ]:
# scalar
 scalar = torch.tensor()
 print(scalar)

IndentationError: ignored

In [ ]:
random_tensor = torch.rand(2,4,3,4)
random_tensor

tensor([[[[0.8107, 0.4374, 0.2287, 0.1210],
          [0.1260, 0.6701, 0.9493, 0.1420],
          [0.7225, 0.0307, 0.4201, 0.9401]],

         [[0.5835, 0.4570, 0.8793, 0.0979],
          [0.4530, 0.5529, 0.4831, 0.4375],
          [0.4285, 0.5771, 0.5988, 0.8437]],

         [[0.1241, 0.2542, 0.3048, 0.7503],
          [0.6805, 0.0826, 0.6070, 0.8667],
          [0.3759, 0.3753, 0.5440, 0.0715]],

         [[0.3178, 0.1989, 0.4551, 0.0533],
          [0.8516, 0.4638, 0.3067, 0.5018],
          [0.7799, 0.4538, 0.4601, 0.7630]]],


        [[[0.0461, 0.2342, 0.1031, 0.0510],
          [0.9846, 0.8701, 0.1806, 0.3378],
          [0.8251, 0.3542, 0.4719, 0.1144]],

         [[0.9410, 0.7185, 0.2879, 0.2855],
          [0.4535, 0.1541, 0.1792, 0.3542],
          [0.4952, 0.3993, 0.1343, 0.2014]],

         [[0.2898, 0.7434, 0.5325, 0.1713],
          [0.5875, 0.2599, 0.4046, 0.9781],
          [0.5132, 0.9432, 0.1854, 0.8241]],

         [[0.2528, 0.2879, 0.9615, 0.7533],
          [0.415

In [ ]:
zeros = torch.zeros(4,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
one_to_number = torch.arange(start = 0, end = 1000, step=100)
print(one_to_number)

ten_zeros = torch.zeros_like(input = one_to_number)
ten_zeros

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])