<a href="https://colab.research.google.com/github/toriqultonu/Learning_PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Sat Oct 21 06:49:12 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
print(torch.__version__)

2.1.0+cu118


## Introduction to Tensors

### Creating Tensors

In [ ]:
random_tensor = torch.rand(2,4,3,4)
random_tensor

In [4]:
zeros = torch.zeros(4,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
one_to_number = torch.arange(start = 0, end = 1000, step=100)
print(one_to_number)

ten_zeros = torch.zeros_like(input = one_to_number)
ten_zeros

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
float_32_tensor = torch.tensor([3.5, 6.7, 9.2])
print(float_32_tensor)

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

print(float_16_tensor * float_32_tensor)

int_32_tensor = torch.tensor([1,345,6,3], dtype = torch.long)
int_32_tensor

tensor([3.5000, 6.7000, 9.2000])
tensor([12.2500, 44.8848, 84.6687])


tensor([  1, 345,   6,   3])

In [8]:
torch.mul(float_32_tensor, 10)

tensor([35., 67., 92.])

In [9]:
## Element wise multiplicaiton:

print(f"element wise multiplicaiton {torch.tensor([1,2,3]) * torch.tensor([1,2,3])}")

element wise multiplicaiton tensor([1, 4, 9])


In [ ]:
## Matrix multiplication
%%time
tensor = torch.rand(3,3,3)
print(tensor)
torch.matmul(tensor, tensor)

In [ ]:
print(tensor)
print(tensor.T)

### Tensor Aggregation

In [ ]:
tensor = torch.randint(0, 100, (8,))
print(tensor)
tensor.float()
print(tensor.dtype)
torch.argmin(tensor)
##torch.mean(tensor.float())

In [1]:
import torch
x = torch.arange(1., 10.)
y = torch.rand(2,3)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [6]:
x_reshaped = x.reshape(3,3)
print(x_reshaped)
z = x_reshaped.view(1,9)
z, x.shape, x_reshaped.shape, z.shape

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([9]),
 torch.Size([3, 3]),
 torch.Size([1, 9]))

In [7]:
## stacking tensor
x_stacked1 = torch.stack([y,y,y,y,y,y], dim=2)
x_stacked2 = torch.stack([x,x,x,x,x,x], dim=1)
x_stacked1, x_stacked2

(tensor([[[0.2939, 0.2939, 0.2939, 0.2939, 0.2939, 0.2939],
          [0.8281, 0.8281, 0.8281, 0.8281, 0.8281, 0.8281],
          [0.0936, 0.0936, 0.0936, 0.0936, 0.0936, 0.0936]],
 
         [[0.5713, 0.5713, 0.5713, 0.5713, 0.5713, 0.5713],
          [0.0433, 0.0433, 0.0433, 0.0433, 0.0433, 0.0433],
          [0.5546, 0.5546, 0.5546, 0.5546, 0.5546, 0.5546]]]),
 tensor([[1., 1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4., 4.],
         [5., 5., 5., 5., 5., 5.],
         [6., 6., 6., 6., 6., 6.],
         [7., 7., 7., 7., 7., 7.],
         [8., 8., 8., 8., 8., 8.],
         [9., 9., 9., 9., 9., 9.]]))

In [13]:
import torch

# Create a tensor with a singleton dimension
x = torch.tensor([[1,3,5]])

# Squeeze the tensor to remove the singleton dimension
y = torch.squeeze(x)

print(x.shape)  # Original shape: (3, 1)
print(y.shape)  # Squeezed shape: (3,)
y

torch.Size([1, 3])
torch.Size([3])


tensor([1, 3, 5])