<a href="https://colab.research.google.com/github/toriqultonu/Learning_PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Sun Oct 22 11:15:38 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
print(torch.__version__)

2.1.0+cu118


## Introduction to Tensors

### Creating Tensors

In [3]:
random_tensor = torch.rand(2,4,3,4)
random_tensor

tensor([[[[0.9868, 0.9047, 0.4761, 0.2940],
          [0.4903, 0.8109, 0.5604, 0.2255],
          [0.7024, 0.7991, 0.6390, 0.1744]],

         [[0.2480, 0.2006, 0.7385, 0.5801],
          [0.2503, 0.0399, 0.1913, 0.8084],
          [0.4135, 0.4840, 0.3333, 0.2026]],

         [[0.7608, 0.9249, 0.4319, 0.6887],
          [0.5412, 0.9124, 0.5889, 0.3920],
          [0.4934, 0.9340, 0.1753, 0.5405]],

         [[0.3775, 0.2630, 0.0947, 0.4566],
          [0.1516, 0.3972, 0.0840, 0.9290],
          [0.6541, 0.1781, 0.7742, 0.8378]]],


        [[[0.7975, 0.9263, 0.3728, 0.4705],
          [0.8620, 0.7835, 0.7365, 0.3987],
          [0.6647, 0.3368, 0.4207, 0.0476]],

         [[0.2107, 0.4458, 0.2058, 0.9672],
          [0.6025, 0.3162, 0.4129, 0.7173],
          [0.4328, 0.0445, 0.7478, 0.3385]],

         [[0.4662, 0.4345, 0.3651, 0.8863],
          [0.5560, 0.4727, 0.9488, 0.8962],
          [0.9944, 0.1253, 0.3082, 0.0054]],

         [[0.8346, 0.3071, 0.2269, 0.5008],
          [0.656

In [4]:
zeros = torch.zeros(4,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
one_to_number = torch.arange(start = 0, end = 1000, step=100)
print(one_to_number)

ten_zeros = torch.zeros_like(input = one_to_number)
ten_zeros

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
float_32_tensor = torch.tensor([3.5, 6.7, 9.2])
print(float_32_tensor)

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

print(float_16_tensor * float_32_tensor)

int_32_tensor = torch.tensor([1,345,6,3], dtype = torch.long)
int_32_tensor

tensor([3.5000, 6.7000, 9.2000])
tensor([12.2500, 44.8848, 84.6687])


tensor([  1, 345,   6,   3])

In [8]:
torch.mul(float_32_tensor, 10)

tensor([35., 67., 92.])

In [9]:
## Element wise multiplicaiton:

print(f"element wise multiplicaiton {torch.tensor([1,2,3]) * torch.tensor([1,2,3])}")

element wise multiplicaiton tensor([1, 4, 9])


In [10]:
## Matrix multiplication
%%time
tensor = torch.rand(3,3,3)
print(tensor)
torch.matmul(tensor, tensor)

tensor([[[0.8530, 0.1389, 0.2121],
         [0.8242, 0.9934, 0.6498],
         [0.2854, 0.9060, 0.0303]],

        [[0.5374, 0.5849, 0.4641],
         [0.9065, 0.9462, 0.8365],
         [0.8870, 0.2727, 0.7811]],

        [[0.7910, 0.6927, 0.7039],
         [0.1743, 0.4278, 0.3671],
         [0.0010, 0.0351, 0.3163]]])
CPU times: user 2.7 ms, sys: 1.15 ms, total: 3.86 ms
Wall time: 6.89 ms


tensor([[[0.9026, 0.4486, 0.2776],
         [1.7073, 1.6901, 0.8401],
         [0.9989, 0.9672, 0.6501]],

        [[1.2307, 0.9943, 1.1012],
         [2.0869, 1.6536, 1.8656],
         [1.4167, 0.9898, 1.2498]],

        [[0.7471, 0.8689, 1.0337],
         [0.2128, 0.3166, 0.3958],
         [0.0072, 0.0268, 0.1136]]])

In [11]:
print(tensor)
print(tensor.T)

tensor([[[0.8530, 0.1389, 0.2121],
         [0.8242, 0.9934, 0.6498],
         [0.2854, 0.9060, 0.0303]],

        [[0.5374, 0.5849, 0.4641],
         [0.9065, 0.9462, 0.8365],
         [0.8870, 0.2727, 0.7811]],

        [[0.7910, 0.6927, 0.7039],
         [0.1743, 0.4278, 0.3671],
         [0.0010, 0.0351, 0.3163]]])
tensor([[[0.8530, 0.5374, 0.7910],
         [0.8242, 0.9065, 0.1743],
         [0.2854, 0.8870, 0.0010]],

        [[0.1389, 0.5849, 0.6927],
         [0.9934, 0.9462, 0.4278],
         [0.9060, 0.2727, 0.0351]],

        [[0.2121, 0.4641, 0.7039],
         [0.6498, 0.8365, 0.3671],
         [0.0303, 0.7811, 0.3163]]])


<ipython-input-11-840264599016>:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3614.)
  print(tensor.T)


### Tensor Aggregation

In [12]:
tensor = torch.randint(0, 100, (8,))
print(tensor)
tensor.float()
print(tensor.dtype)
torch.argmin(tensor)
##torch.mean(tensor.float())

tensor([57, 65, 61, 50, 61, 47, 69,  6])
torch.int64


tensor(7)

In [13]:
import torch
x = torch.arange(1., 10.)
y = torch.rand(2,3)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [14]:
x_reshaped = x.reshape(3,3)
print(x_reshaped)
z = x_reshaped.view(1,9)
z, x.shape, x_reshaped.shape, z.shape

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([9]),
 torch.Size([3, 3]),
 torch.Size([1, 9]))

In [15]:
## stacking tensor
x_stacked1 = torch.stack([y,y,y,y,y,y], dim=2)
x_stacked2 = torch.stack([x,x,x,x,x,x], dim=1)
x_stacked1, x_stacked2

(tensor([[[0.3890, 0.3890, 0.3890, 0.3890, 0.3890, 0.3890],
          [0.2566, 0.2566, 0.2566, 0.2566, 0.2566, 0.2566],
          [0.1028, 0.1028, 0.1028, 0.1028, 0.1028, 0.1028]],
 
         [[0.5840, 0.5840, 0.5840, 0.5840, 0.5840, 0.5840],
          [0.1360, 0.1360, 0.1360, 0.1360, 0.1360, 0.1360],
          [0.1345, 0.1345, 0.1345, 0.1345, 0.1345, 0.1345]]]),
 tensor([[1., 1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4., 4.],
         [5., 5., 5., 5., 5., 5.],
         [6., 6., 6., 6., 6., 6.],
         [7., 7., 7., 7., 7., 7.],
         [8., 8., 8., 8., 8., 8.],
         [9., 9., 9., 9., 9., 9.]]))

In [16]:
import torch

# Create a tensor with a singleton dimension
x = torch.tensor([[1,3,5]])

# Squeeze the tensor to remove the singleton dimension
y = torch.squeeze(x)

print(x.shape)  # Original shape: (3, 1)
print(y.shape)  # Squeezed shape: (3,)
y

torch.Size([1, 3])
torch.Size([3])


tensor([1, 3, 5])

In [21]:
z = y.unsqueeze(dim=1)
z.shape

torch.Size([3, 1])

In [23]:
x = torch.randn(2,3,5);
y = torch.permute(x,(2,0,1))
x, y

(tensor([[[ 0.4551, -0.8082,  0.0542,  0.1967, -0.1777],
          [-1.0545, -1.1442, -0.8540, -0.2823, -2.0665],
          [ 1.2644, -0.9647,  1.6327, -0.0268, -0.3928]],
 
         [[-0.6240,  0.2350, -1.3711,  0.2733, -2.4156],
          [ 0.0696, -0.3790,  0.4543,  0.9560, -1.5150],
          [ 1.4256, -0.9252, -1.8322,  0.0532, -0.1417]]]),
 tensor([[[ 0.4551, -1.0545,  1.2644],
          [-0.6240,  0.0696,  1.4256]],
 
         [[-0.8082, -1.1442, -0.9647],
          [ 0.2350, -0.3790, -0.9252]],
 
         [[ 0.0542, -0.8540,  1.6327],
          [-1.3711,  0.4543, -1.8322]],
 
         [[ 0.1967, -0.2823, -0.0268],
          [ 0.2733,  0.9560,  0.0532]],
 
         [[-0.1777, -2.0665, -0.3928],
          [-2.4156, -1.5150, -0.1417]]]))

In [1]:
## Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [1]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [2]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

# Count number of devices
torch.cuda.device_count()

1

In [4]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

tensor([1, 2, 3]) cpu


TypeError: ignored

In [5]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])