<a href="https://colab.research.google.com/github/toriqultonu/Learing_PyTorch/blob/main/learing_pytorch_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

!nvidia-smi

1.13.1+cu116
Wed Mar 22 16:41:23 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P0    28W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                           

In [14]:
## Introduction to tensors..

# creating tensors
# scalar

scalar = torch.tensor(7) 
scalar

tensor(7)

In [15]:
scalar.ndim

0

In [16]:
# get tensor back as python int 

scalar.item()

7

In [17]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [18]:
vector.ndim

1

In [19]:
vector.shape

torch.Size([2])

In [22]:
# MATRIX
MATRIX = torch.tensor([[7, 8], 
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [24]:
MATRIX.ndim

2

In [25]:
MATRIX[1]

tensor([ 9, 10])

In [26]:
MATRIX.shape

torch.Size([2, 2])

In [28]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [30]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
### Random tensors

