# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [6]:
# Import torch
import torch

# Create random tensor
torch.manual_seed(seed = 0)
tensor = torch.rand(7,4)
tensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939, 0.5185],
        [0.6977, 0.8000, 0.1610, 0.2823],
        [0.6816, 0.9152, 0.3971, 0.8742],
        [0.4194, 0.5529, 0.9527, 0.0362]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
torch.manual_seed(seed = 0)
tensor2 = torch.rand(4,1)
# Perform matrix multiplication

torch.matmul(tensor,tensor2)

tensor([[0.8617],
        [0.8014],
        [0.7958],
        [0.2353],
        [1.0123],
        [1.1919],
        [0.7220]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed


# Create two random tensors


# Matrix multiply tensors


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
random_seed = 1234
torch.cuda.manual_seed(random_seed)
tensor1 = torch.rand(3,5)

torch.cuda.manual_seed(random_seed)
tensor2 = torch.rand(3,5)

tensor1 == tensor2

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [15]:
# Set random seed
torch.manual_seed(1234)
tensor1 = torch.rand(2,3)

torch.manual_seed(1234)
tensor2 = torch.rand(2,3)

# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
tensorA = tensor1.to("cuda")
tensorB = tensor2.to("cuda")
tensorA, tensorB

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [19]:
# Perform matmul on tensor_A and tensor_B
mul = torch.matmul(tensorA, tensorB.T)
mul

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [20]:
# Find max
torch.max(mul)
# Find min
torch.min(mul)

tensor(0.2161, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [21]:
# Find arg max
torch.argmax(mul)

# Find arg min
torch.argmin(mul)

tensor(1, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [28]:
# Set seed
seed  = 7

# Create random tensor
torch.manual_seed(seed)
tensor1 = torch.rand(1,1,1,10)
torch.manual_seed(seed)
tensor2 = torch.rand(1,1,1,10)

# Remove single dimensions
squeezed1 = tensor1.squeeze()
squeezed2 = tensor2.squeeze()
# Print out tensors and their shapes
tensor1, squeezed1.shape, tensor2, squeezed2.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([10]),
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([10]))