<a href="https://colab.research.google.com/github/toriqultonu/Learning_PyTorch/blob/main/learing_pytorch_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

!nvidia-smi

1.13.1+cu116
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
## Introduction to tensors..

# creating tensors
# scalar

scalar = torch.tensor(7) 
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int 

scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8], 
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
### Random tensors
# crete a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor
random_tensor.ndim

2

In [ ]:
# create random tensor for images

random_image_tensor = torch.rand(size=(3, 224, 224))
random_image_tensor.ndim

3

In [ ]:
# create zero tensor

zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor
zeros.dtype

torch.float32

In [ ]:
# use torch.range()
torch.arange(0,10)

one_to_ten = torch.arange(start = 1, end = 1000, step = 100)

In [ ]:
# creating tensors like
ten_zeros = torch.zeros_like(input = random_tensor)
ten_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [1]:
# creating float 32 tensors
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16)
float_32_tensor.dtype

NameError: ignored

In [1]:
import torch
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

tensor = torch.tensor([1,2,3], device=device)

print(tensor, tensor.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


In [2]:
!nvidia-smi

Sun Mar 26 23:24:06 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P0    29W /  70W |    573MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------